// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/email.proto

package email

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailTarget   string                 `protobuf:"bytes,1,opt,name=emailTarget,proto3" json:"emailTarget,omitempty"`
	MessageText   string                 `protobuf:"bytes,2,opt,name=messageText,proto3" json:"messageText,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=contentType,proto3" json:"contentType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_api_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_api_email_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmailTarget() string {
	if x != nil {
		return x.EmailTarget
	}
	return ""
}

func (x *EmailRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *EmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_api_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_api_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_email_proto protoreflect.FileDescriptor

const file_api_email_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/email.proto\x12\x05email\"\x8e\x01\n" +
	"\fEmailRequest\x12 \n" +
	"\vemailTarget\x18\x01 \x01(\tR\vemailTarget\x12 \n" +
	"\vmessageText\x18\x02 \x01(\tR\vmessageText\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12 \n" +
	"\vcontentType\x18\x04 \x01(\tR\vcontentType\"?\n" +
	"\rEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2A\n" +
	"\fEmailService\x121\n" +
	"\x04Send\x12\x13.email.EmailRequest\x1a\x14.email.EmailResponseB\x16Z\x14./pkg/emailpb/;emailb\x06proto3"

var (
	file_api_email_proto_rawDescOnce sync.Once
	file_api_email_proto_rawDescData []byte
)

func file_api_email_proto_rawDescGZIP() []byte {
	file_api_email_proto_rawDescOnce.Do(func() {
		file_api_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_email_proto_rawDesc), len(file_api_email_proto_rawDesc)))
	})
	return file_api_email_proto_rawDescData
}

var file_api_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_email_proto_goTypes = []any{
	(*EmailRequest)(nil),  // 0: email.EmailRequest
	(*EmailResponse)(nil), // 1: email.EmailResponse
}
var file_api_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.Send:input_type -> email.EmailRequest
	1, // 1: email.EmailService.Send:output_type -> email.EmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_email_proto_init() }
func file_api_email_proto_init() {
	if File_api_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_email_proto_rawDesc), len(file_api_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_email_proto_goTypes,
		DependencyIndexes: file_api_email_proto_depIdxs,
		MessageInfos:      file_api_email_proto_msgTypes,
	}.Build()
	File_api_email_proto = out.File
	file_api_email_proto_goTypes = nil
	file_api_email_proto_depIdxs = nil
}
