name: CI
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

  tests:
    needs: linter
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run tests
        run: |
          go test ./tests/

  build:
    needs: tests
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build image
        run: |
          docker build .
